apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-db-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ if hasKey .Values.secrets.database "user" }}{{ .Values.secrets.database.user | b64enc }}{{ else }}{{ "reana" | b64enc }}{{ end }}
  password: {{ if hasKey .Values.secrets.database "password" }}{{ .Values.secrets.database.password | b64enc }}{{ else }}{{ "reana" | b64enc }}{{ end }}
