apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-cern-gitlab-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_GITLAB_OAUTH_APP_ID: {{ if hasKey .Values.secrets.gitlab "REANA_GITLAB_OAUTH_APP_ID" }}{{ .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_ID | b64enc }}{{ else }}{{ "reana_gitlab_oauth_app_id" | b64enc }}{{ end }}
  REANA_GITLAB_OAUTH_APP_SECRET: {{ if hasKey .Values.secrets.gitlab "REANA_GITLAB_OAUTH_APP_SECRET" }}{{ .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_SECRET | b64enc }}{{ else }}{{ "reana_gitlab_oauth_app_secret" | b64enc }}{{ end }}
  REANA_GITLAB_HOST: {{ if hasKey .Values.secrets.gitlab "REANA_GITLAB_HOST" }}{{ .Values.secrets.gitlab.REANA_GITLAB_HOST | b64enc }}{{ else }}{{ "gitlab.cern.ch" | b64enc }}{{ end }}
