{{- if .Values.login }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-login-provider-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  PROVIDER_SECRETS: {{ .Values.secrets.login | toJson | b64enc }}
{{- end }}
