{{- if .Values.notifications.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-mail-notification-sender-password
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_EMAIL_LOGIN: {{ .Values.notifications.email_config.login | default "" | b64enc | quote }}
  REANA_EMAIL_PASSWORD: {{ .Values.notifications.email_config.password | default "" | b64enc | quote }}
{{- end }}
