apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-message-broker-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ if hasKey .Values.secrets.message_broker "user" }}{{ .Values.secrets.message_broker.user | b64enc | quote }}{{ else }}{{ "test" | b64enc | quote }}{{ end }}
  password: {{ if hasKey .Values.secrets.message_broker "password" }}{{ .Values.secrets.message_broker.password | b64enc | quote }}{{ else }}{{ "1234" | b64enc | quote }}{{ end }}
