{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-opensearch-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_OPENSEARCH_PASSWORD: {{ if hasKey .Values.secrets.opensearch "password" }}{{ .Values.secrets.opensearch.password | b64enc }}{{ else }}{{ "reana" | b64enc }}{{ end }}
  {{- if not .Values.opensearch.securityConfig.enabled }}
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ if hasKey .Values.opensearch "initialAdminPassword" }}{{ .Values.opensearch.initialAdminPassword | b64enc }}{{ else }}{{ "reana" | b64enc }}{{ end }} # dev environment only
  {{- end }}
{{- end }}
