apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-cern-sso-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  CERN_CONSUMER_KEY: {{ if hasKey .Values.secrets.cern.sso "CERN_CONSUMER_KEY" }}{{ .Values.secrets.cern.sso.CERN_CONSUMER_KEY | b64enc }}{{ else }}{{ "cern_consumer_key" | b64enc }}{{ end }}
  CERN_CONSUMER_SECRET: {{ if hasKey .Values.secrets.cern.sso "CERN_CONSUMER_SECRET" }}{{ .Values.secrets.cern.sso.CERN_CONSUMER_SECRET | b64enc }}{{ else }}{{ "cern_consumer_secret" | b64enc }}{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-eosc-sso-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  EOSC_CONSUMER_KEY: {{ if hasKey .Values.secrets.eosc.sso "EOSC_CONSUMER_KEY" }}{{ .Values.secrets.eosc.sso.EOSC_CONSUMER_KEY | b64enc }}{{ else }}{{ "eosc_consumer_key" | b64enc }}{{ end }}
  EOSC_CONSUMER_SECRET: {{ if hasKey .Values.secrets.eosc.sso "EOSC_CONSUMER_SECRET" }}{{ .Values.secrets.eosc.sso.EOSC_CONSUMER_SECRET | b64enc }}{{ else }}{{ "eosc_consumer_secret" | b64enc }}{{ end }}
