{{- if and .Values.ingress.enabled .Values.ingress.tls.self_signed_cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-tls-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  {{- $cert := genSelfSignedCert (.Values.reana_hostname) nil nil 90 }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end }}
